### ISSUE TITLE
Content headers in monograph are not navigating if the headers title starts with numbers

### ISSUE THREAD

**Issue by Madhan-kumar-selvaraj** [streetwriters/notesnook#2651]
### What happened?

![image](https://github.com/streetwriters/notesnook/assets/59301245/94780895-8548-4d11-a7ec-5ae503f36ac0)

- Created a note with multiple headings and added numerical numbers in front of it to sort the topics easily.
- I published the notes through monograph and tried clicking the headings from the content but it's not navigating to the respective heading. I tried without adding numbers and it's working fine.
- Also, it'll be better to have Table of content at the read-only mode or by default
- For reference https://monograph.notesnook.com/647b29467c7c7c7bf69393a6/

### Steps to reproduce the problem

1. Create a note with headers by adding numbers at the beginning
2. Add some headers and content
3. Publish the note
4. Click on the contents headers on the right side of the note.
5. Check whether it's navigating to respective header or not

### Version

2.5.0

### Platform/OS

Firefox

**Comment by ammarahm-ed** [comment]
Hey, this issue has been fixed on the monograph website now! thanks for reporting.

**Comment by Madhan-kumar-selvaraj** [comment]
How much time does it take to reflect this feature?

**Comment by ammarahm-ed** [comment]
> How much time does it take to reflect this feature? Facing same issue right now.

Can you try now?

**Comment by Madhan-kumar-selvaraj** [comment]
Still the bug is not fixed – Check with this monograph https://monograph.notesnook.com/6479b50fe8e8e865ca61623b/

**Comment by thecodrr** [comment]
@Madhan-kumar-selvaraj should be deployed and fixed now.

**Comment by Madhan-kumar-selvaraj** [comment]
It's working fine. This is the one and only app that expects new features and bugs from the user and giving a quick response to them. By soon, you people will reach a great height.
