### ISSUE TITLE
[Flatpak] Crash on wayland when maximizing app in KDE Plasma 5.27.8

### ISSUE THREAD

**Issue by zestygrass** [streetwriters/notesnook#3401]
### What happened?

Flatpak version no longer runs. I tried doing a clean install, removed all data, rebooted and reinstalled the app. After initially working for the first run, it won't open again. See the log for error message.

### Steps to reproduce the problem

1. flatpak run com.notesnook.Notesnook.
2. App should open on first attempt.
3. closing and reopening the app does not work again.

### Version

2.6.4

### Platform/OS

Linux

### Relevant log output

```shell
flatpak run com.notesnook.Notesnook
[3:0919/132523.567228:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0919/132523.912686:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0919/132523.912730:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
App ready. Opening window.
https protocol inteception "successful"
/app/bin/start-notesnook: line 2:     3 Segmentation fault      (core dumped) zypak-wrapper.sh /app/bin/notesnook --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations "$@"
```

**Comment by thecodrr** [comment]
@zestygrass is this wayland or x11?

**Comment by zestygrass** [comment]
wayland on kde plasma 5.27.8, Arch linux base.
let me know if you need me to do anything to help with replicating the bug

**Comment by zestygrass** [comment]
I reinstalled the app again, got it to reopen after first run. 
I may have found a clue as to why it was not opening before. After opening the app again, I tried to maximize it by clicking on the maximize button and that crashes it every time. I had the app maximized during it's initial run before, which likely caused it to keep crashing when opening. Likely a window decoration bug?

Logs:

```
> 
> flatpak run com.notesnook.Notesnook
> [3:0920/151316.055255:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [3:0920/151316.335714:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [3:0920/151316.335752:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> App ready. Opening window.
> https protocol inteception "successful"
> Intercepting request: https://app.notesnook.com/
> Intercepting request: https://app.notesnook.com/assets/index-d19c6ac6.js
> Intercepting request: https://app.notesnook.com/assets/index-00536d7a4c5a.css
> Intercepting request: https://app.notesnook.com/assets/nncrypto.worker-9e2f891e.js
> Intercepting request: https://app.notesnook.com/assets/index-fb491cc7200a.js
> Intercepting request: https://app.notesnook.com/assets/total-notes-0549a64434af.js
> Intercepting request: https://app.notesnook.com/assets/string-ea2683193803.js
> Intercepting request: https://app.notesnook.com/assets/random-4b33b3b0ddaf.js
> Intercepting request: https://app.notesnook.com/assets/toast-acd58581e048.js
> Intercepting request: https://app.notesnook.com/assets/index-4f390db818eb.js
> Intercepting request: https://app.notesnook.com/assets/browser-a0291a37f3e5.js
> Intercepting request: https://app.notesnook.com/assets/toast-dea4ca770e0f.css
> Intercepting request: https://app.notesnook.com/assets/compressor-2244a1d7653d.js
> Intercepting request: https://app.notesnook.com/assets/network-check.worker-aed75908.js
> Intercepting request: https://app.notesnook.com/assets/app-08e51c8f678d.js
> Intercepting request: https://app.notesnook.com/assets/index-dd4858f03c30.js
> Intercepting request: https://app.notesnook.com/assets/index-315f20d48686.js
> Intercepting request: https://app.notesnook.com/assets/index-45e3532fe5d0.js
> Intercepting request: https://app.notesnook.com/assets/body-87b607ed0671.js
> Intercepting request: https://app.notesnook.com/assets/index-0c07cdbefb90.css
> Intercepting request: https://app.notesnook.com/assets/use-persistent-state-99741bc2a350.js
> Intercepting request: https://app.notesnook.com/assets/index-ee81d7812f8a.js
> Intercepting request: https://app.notesnook.com/assets/app-effects-fe8443bbdb1f.js
> Intercepting request: https://app.notesnook.com/assets/onboarding-dialog-cf03fb21d7ef.js
> Intercepting request: https://app.notesnook.com/assets/nomad-0a98644240e4.js
> Intercepting request: https://app.notesnook.com/assets/index-aa1e6b90aab6.js
> Intercepting request: https://app.notesnook.com/assets/index-4ed41de2ff70.js
> Intercepting request: https://app.notesnook.com/assets/index-aa03c5c8ae27.js
> Intercepting request: https://app.notesnook.com/assets/picker-3de37fb52c7a.js
> Intercepting request: https://app.notesnook.com/assets/index-d447bca0814a.css
> Intercepting request: https://app.notesnook.com/assets/open-sans-v34-vietnamese_latin-ext_latin_hebrew_greek-ext_greek_cyrillic-ext_cyrillic-regular-52a27a6a1c18.woff2
> APPIMAGE env is not defined, current application is not an AppImage
> Intercepting request: https://app.notesnook.com/assets/open-sans-v34-vietnamese_latin-ext_latin_hebrew_greek-ext_greek_cyrillic-ext_cyrillic-600-0240d31750de.woff2
> Intercepting request: https://app.notesnook.com/assets/feature-dialog-33c47f54ad74.js
> /app/bin/start-notesnook: line 2:     3 Segmentation fault      (core dumped) zypak-wrapper.sh /app/bin/notesnook --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations "$@"
```

**Comment by thecodrr** [comment]
@zestygrass i think all these bugs are due to buggy wayland support in Electron. It might get fixed by an Electron version upgrade. Unfortunately, Linux is not a huge focus for Electron because Electron 26 is completely broken on Linux, and 27 is still in Beta.

**Comment by zestygrass** [comment]
Electron support for linux has been spotty forever, at least I know the what the problem is now.

**Comment by thecodrr** [comment]
@zestygrass can you check this issue again on v2.6.8? I updated the electron version so this could potentially be fixed.

**Comment by zestygrass** [comment]
I'm still on version 2.6.4, I check the flathub website, that's the version it shows on the website as well. The flathub repo for notesnook is at 2.6.7? 
maybe updates are not propagating? 

I checked for updates again, just to be sure.
![Uploading Screenshot_20231102_174846.png…](img)

**Comment by zestygrass** [comment]
Updates to 2.6.8 today, maximizing still crashes the app, but the app does reopen just fine, won't crash on reopening, unless I try to maximize it again, which causes it to crash.

**Comment by thecodrr** [comment]
@zestygrass try now, the update should be live on Flathub.

**Comment by mufeedali** [comment]
I can confirm that this issue is still present.

**Comment by securityboxtc** [comment]
Issue still present for me as well, but I no longer need to maximize/interact with the app before it crashes. The app closes itself before login is even complete.

Flatpak app version 3.0.3; KDE version 5.27.5; Debian 12 stable.
