### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#425]
**Describe the bug**

Everything I have done on my desktop for the past few hours is refusing to sync to mobile. Here are the logs:

```
Error: An unknown error occured.
    at construct (native)
    at Wrapper (address at index.android.bundle:1:153047)
    at construct (native)
    at _createSuperInternal (address at index.android.bundle:1:1017268)
    at call (native)
    at RequestError (address at index.android.bundle:1:1019872)
    at handleResponse$ (address at index.android.bundle:1:1018310)
    at call (native)
    at tryCatch (address at index.android.bundle:1:163284)
    at invoke (address at index.android.bundle:1:164288)
    at anonymous (address at index.android.bundle:1:163432)
    at call (native)
    at tryCatch (address at index.android.bundle:1:163284)
    at invoke (address at index.android.bundle:1:163517)
    at anonymous (address at index.android.bundle:1:163729)
    at tryCallOne (/tmp/hermes/staging/hermes/cmake/intlRelease/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/tmp/hermes/staging/hermes/cmake/intlRelease/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:170030)
    at _callTimer (address at index.android.bundle:1:168929)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:169133)
    at callReactNativeMicrotasks (address at index.android.bundle:1:171121)
    at callReactNativeMicrotasks (address at index.android.bundle:1:76386)
    at anonymous (address at index.android.bundle:1:75471)
    at guard (address at index.android.bundle:1:76227)
    at flushedQueue (address at index.android.bundle:1:75382)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:75325)
```
**Desktop:**
 - OS: Arch Linux
 - Browser: Electron
 - Version: 1.8.2

**Smartphone:**
 - Device: Samsung Galaxy S10+
 - OS: Android 12
 - Version: 1.8.3

**Comment by thecodrr** [comment]
Is it syncing from desktop?

**Comment by candroid-man** [comment]
Yes

**Comment by thecodrr** [comment]
This could be a session expired error. There is a known bug in the error handling where it doesn't correctly detect what happened (fixed now though but not released yet).

If it continues to appear, that's probably it. The next question would be when did you last use the mobile app? The session expires if the app isn't opened for 15-30 days.

**Comment by candroid-man** [comment]
I was using it yesterday and the day before that

**Comment by thecodrr** [comment]
Can you try running a force sync?

**Comment by candroid-man** [comment]
Just did, still no effect. Now when I try doing a simple swipe-down refresh sync, the error no longer appears but none of my stuff is synced

**Comment by thecodrr** [comment]
Okay if the error isn't appearing that's good. Try force syncing from desktop too.

**Comment by candroid-man** [comment]
Force synced on both devices, and have restarted both clients once again. I still do not see any of my stuff from desktop on mobile

**Comment by thecodrr** [comment]
What does the sync status read?

**Comment by candroid-man** [comment]
Errors are back, it says it was last synced 2 days ago on mobile, 5 minutes ago on desktop

**Comment by thecodrr** [comment]
Okay so mobile isn't syncing. If there aren't any unsynced changes on mobile try logging out and logging back in.

**Comment by candroid-man** [comment]
Logging out and logging back in fixed the issue. Will the new update fix this issue, or are you still unsure as to the cause?

**Comment by thecodrr** [comment]
I am pretty sure it was a session expiry issue. The bug will be fixed in the next release. However, the weird thing is why the error came in the first place.

**Comment by candroid-man** [comment]
Yeah, because I have been using both to find bugs for the past few days. We'll get to the bottom of it, I'm sure

**Comment by candroid-man** [comment]
@thecodrr the issue is back. Since i was able to sync after relogging, I am having the same problem where I cannot get anything to sync. No errors this time around as far as I know

**Comment by thecodrr** [comment]
Fixed in v1.8.4
